### ISSUE TITLE
NPE on startup

### ISSUE THREAD

**Issue by SlimeDog** [Phoenix616/NamechangeSimulator#2]
Spigot 1.13.2 latest
NamechangeSimulator 1.1.1-b10

```
[16:20:12] [Server thread/INFO]: [NamechangeSimulator] Enabling NamechangeSimulator v1.1.1-SNAPSHOT (build 10)
[16:20:12] [Server thread/INFO]: [NamechangeSimulator] Loading fake names from config...
[16:20:12] [Server thread/ERROR]: Error occurred while enabling NamechangeSimulator v1.1.1-SNAPSHOT (build 10) (Is it up to date?)
java.lang.NullPointerException: null
        at de.themoep.namechangesimulator.NamechangeSimulator.onEnable(NamechangeSimulator.java:61) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254) ~[spigot-1.13.2.jar-2019-01-14-0809:git-Spigot-f56e2e7-0c715b3]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.13.2.jar-2019-01-14-0809:git-Spigot-f56e2e7-0c715b3]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot-1.13.2.jar-2019-01-14-0809:git-Spigot-f56e2e7-0c715b3]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:434) [spigot-1.13.2.jar-2019-01-14-0809:git-Spigot-f56e2e7-0c715b3]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:348) [spigot-1.13.2.jar-2019-01-14-0809:git-Spigot-f56e2e7-0c715b3]
        at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:214) [spigot-1.13.2.jar-2019-01-14-0809:git-Spigot-f56e2e7-0c715b3]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:698) [spigot-1.13.2.jar-2019-01-14-0809:git-Spigot-f56e2e7-0c715b3]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

Directory _plugins/NamechangeSimulator/_ was not created, so file _plugins/NamechangeSimulator/config.yml_ does not exist.

The NPE is generated on subsequent server starts, even though config.yml does exist (with appropriate content).

Plugin features seem to work correctly, despite NPE.

**Comment by SlimeDog** [comment]
The NPE is generated on subsequent server starts, even though _config.yml_ does exist (with appropriate content).
